# my global config
global:
  scrape_interval: 60s
  evaluation_interval: 60s


rule_files: []

scrape_configs:
  - job_name: 'self-metrics'
    scheme: http
    scrape_timeout: 10s
    metrics_path: "/metrics"
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: 
        - "node-exporter:9100"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.*):\d+
        replacement: ${1}

  - job_name: "mikrotik"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "mktxp:49090"

  - job_name: "blackbox"
    scrape_interval: 1s
    metrics_path: /probe
    params:
      module: [icmp_ttl5]
    static_configs:
      - targets:
          - 1.1.1.1
          - 8.8.8.8
          - 9.9.9.9

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'grafana_metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['grafana:3000']
