volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/prometheus

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: mon-prometheus
    labels:
      org.label-schema.group: "monitoring"
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1y"    # <= adjust the storage retention period of Prometheus
      - "--storage.tsdb.retention.size=10GB"  # <= adjust the storage retention size of Prometheus
      - "--web.enable-lifecycle"              # enable hot reload via POST /-/reload
    restart: unless-stopped
    networks:
      - monitoring
    expose:
      - "9090"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: mon-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    container_name: mon-blackbox-exporter
    command: --config.file=/config/blackbox.yaml
    volumes:
      - ./configs/blackbox/blackbox.yaml:/config/blackbox.yaml
    networks:
      - monitoring
    restart: unless-stopped