volumes:
  grafana_data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/grafana

services:
  grafana:
    image: grafana/grafana:11.4.0
    container_name: mon-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=flant-statusmap-panel
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
